DROP TABLE IF EXISTS RESERVATIONS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS HOUSINGS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(200) NOT NULL,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(20) NOT NULL,
	locality VARCHAR(20) NOT NULL,
	phoneNumber INT NOT NULL,
	email VARCHAR(500) NOT NULL,
	birthDate DATETIME NOT NULL,
	role TINYINT NOT NULL
);

CREATE TABLE HOUSINGS (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	housingCode BIGINT NOT NULL,
	type VARCHAR(30) NOT NULL,
	numberOfRooms INTEGER NOT NULL,
	pricePerNight DECIMAL(10, 2) NOT NULL,
	description VARCHAR(500) NOT NULL,
	breakfast BOOLEAN NOT NULL,
	lunch BOOLEAN NOT NULL,
	dinner BOOLEAN NOT NULL,
	score DOUBLE(10, 2),
	available BOOLEAN NOT NULL,
	location VARCHAR(40) NOT NULL,
	ownerId BIGINT NOT NULL,
	CONSTRAINT OwnerIdFK FOREIGN KEY(ownerId)
	REFERENCES Users(id)
);

CREATE TABLE REVIEWS (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL, 
	body VARCHAR(500) NOT NULL,
	locationScore DOUBLE(10,2) NOT NULL,
	serviceScore DOUBLE(10,2) NOT NULL,
	wifiScore DOUBLE(10,2) NOT NULL,
	foodScore DOUBLE(10,2) NOT NULL,
	cleaningScore DOUBLE(10,2) NOT NULL,
	totalScore DOUBLE(10, 2) NOT NULL,
	publicationDate DATETIME NOT NULL,
	authorId BIGINT NOT NULL,
	housingId BIGINT NOT NULL,
	CONSTRAINT AuthorIdFK FOREIGN KEY(authorId)
	REFERENCES Users(id),
	CONSTRAINT HousingIdFK FOREIGN KEY(housingId)
	REFERENCES Housings(id)
);

CREATE TABLE RESERVATIONS (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	reservationCode BIGINT NOT NULL,
	checkIn DATETIME NOT NULL,
	checkOut DATETIME NOT NULL,
	paymentMethod VARCHAR(50) NOT NULL,
	reservationDate DATETIME NOT NULL,
	totalPrice DECIMAL NOT NULL,
	checkedIn BOOLEAN NOT NULL,
	customerId BIGINT NOT NULL,
	housingId BIGINT NOT NULL,
	CONSTRAINT CustomerIdFK FOREIGN KEY(customerId)
	REFERENCES Users(id),
	CONSTRAINT HousingIdFK2 FOREIGN KEY(housingId)
	REFERENCES Housings(id)
);
	
	